### ISSUE TITLE
Wont process pass 20%

### ISSUE THREAD

**Issue by martel80** [ZFTurbo/MVSEP-MDX23-music-separation-model#1]
WIN 10 22H2
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 
16GB RAM

GPU: RTX 3060

I tried with GPU and CPU.

With CPU, it freeze at 20% (it take about 5 minute to go to 20%) and nothing happen. When you click something , anything, the whole thing crash.

With GPU, the whole thing crash including the cmd prompt window when reaching 20%

See CMD Prompt logs:

**CPU Rendering:**

C:\Users\****\*******\MVSep-MDX23>"./Miniconda/python.exe" gui.py
GPU use: 0
Use device: cpu
Model path: C:\Users\****\*******\MVSep-MDX23/models/Kim_Vocal_1.onnx
Device: cpu Chunk size: 200000000
Model path: C:\Users\****\*******\MVSep-MDX23/models/Kim_Inst.onnx
Device: cpu Chunk size: 200000000
Go for: C:/Users/*****/OneDrive/Musique/Album/Sean Price, M-Phazes/[E] Land of the Crooks [148615077] [2013]/01 - Sean Price, M-Phazes - Bag of Shit (feat. Loudmouf Choir)(Explicit).flac
Input audio: (2, 7537326) Sample rate: 44100
C:\Users\******\Downloads\MVSep-MDX23\inference.py:128: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  mix_waves = torch.tensor(mix_waves, dtype=torch.float32).to(device)
  
  **GPU Rendering:**
  
  C:\Users\******\Downloads\MVSep-MDX23>"./Miniconda/python.exe" gui.py
GPU use: 0
Use device: cuda:0
Model path: C:\Users\********\Downloads\MVSep-MDX23/models/Kim_Vocal_1.onnx
Device: cuda:0 Chunk size: 1000000
Model path: C:\Users\*******\Downloads\MVSep-MDX23/models/Kim_Inst.onnx
Device: cuda:0 Chunk size: 1000000
Go for: C:/Users/*******/OneDrive/Musique/Album/Sean Price, M-Phazes/[E] Land of the Crooks [148615077] [2013]/01 - Sean Price, M-Phazes - Bag of Shit (feat. Loudmouf Choir)(Explicit).flac
Input audio: (2, 7537326) Sample rate: 44100
C:\Users\*******\Downloads\MVSep-MDX23\inference.py:128: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  mix_waves = torch.tensor(mix_waves, dtype=torch.float32).to(device)
2023-05-12 13:20:55.9949877 [E:onnxruntime:, sequential_executor.cc:494 onnxruntime::ExecuteKernel] Non-zero status code returned while running FusedConv node. Name:'Conv_3' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 603979776

Traceback (most recent call last):
  File "C:\Users\********\Downloads\MVSep-MDX23\gui.py", line 36, in run
    predict_with_model(self.options)
  File "C:\Users\*********\Downloads\MVSep-MDX23\inference.py", line 479, in predict_with_model
    result, sample_rates = model.separate_music_file(audio.T, sr, update_percent_func, i, len(options['input_audio']))
  File "C:\Users\********\Downloads\MVSep-MDX23\inference.py", line 344, in separate_music_file
    sources1 = demix_full(
  File "C:\Users\********\Downloads\MVSep-MDX23\inference.py", line 160, in demix_full
    sources = demix_base(mix_part, device, models, infer_session)
  File "C:\Users\********\Downloads\MVSep-MDX23\inference.py", line 133, in demix_base
    res = _ort.run(None, {'input': stft_res.cpu().numpy()})[0]
  File "C:\Users\********\Downloads\MVSep-MDX23\Miniconda\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedConv node. Name:'Conv_3' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 603979776

**Comment by MaxCoo** [comment]
WIN 11 22H2
13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
64 GB RAM

GPU: RTX 4080

Tried only on GPU using the GUI / console process.

Same as [martel80](https://github.com/martel80) but reach 60% (very slow, 10/15 min) before getting memory crash.

I will test on CPU.

**Comment by ZFTurbo** [comment]
In settings set 'single onnx' will resolve issue if you have less than 12 GB of GPU memory. Quality degrade just a little bit.

I will rewrote the code to consume less GPU.

**Comment by sanskar-mk2** [comment]
Hello friend, can you also give chunk size slider in the gui please. I try to use it with default settings and my GPU is super making noise.

![image](https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/assets/100945489/5f36b2ad-cf52-488f-b48c-d5d1122b89aa)

**Comment by martel80** [comment]
> In settings set 'single onnx' will resolve issue if you have less than 12 GB of GPU memory. Quality degrade just a little bit.
> 
> I will rewrote the code to consume less GPU.

It still failed here. It crashed a bit after 20% this time.

**Comment by MaxCoo** [comment]
> > In settings set 'single onnx' will resolve issue if you have less than 12 GB of GPU memory. Quality degrade just a little bit.
> > I will rewrote the code to consume less GPU.
> 
> It still failed here. It crashed a bit after 20% this time.

In the `gui.py` file, line 142, you have an array for the default settings.

```
options = {
            'input_audio': root['input_files'],
            'output_folder': root['output_folder'],
            'cpu': root['cpu'],
            'single_onnx': root['single_onnx'],
            'overlap_large': 0.6,
            'overlap_small': 0.5,
        }
```

Just add a new option called `chunk_size` for settings a lower value, here I use 10000. I don't know if the value impact the performances, but you will not have crash anymore I think.

```
        options = {
            'input_audio': root['input_files'],
            'output_folder': root['output_folder'],
            'cpu': root['cpu'],
            'single_onnx': root['single_onnx'],
            'overlap_large': 0.6,
            'overlap_small': 0.5,
            'chunk_size': 10000,
        }
```

**Comment by lucellent** [comment]
I can't fix this issue even with chunk size = 1000 and single ONNx enabled... I have 3070 with 8GB VRAM

**Comment by lucellent** [comment]
Sadly I still get the issue, even with chunk size 500 and single onnx

**Comment by ZFTurbo** [comment]
> Sadly I still get the issue, even with chunk size 500 and single onnx

Are you sure you updated code? Do you have a message in log: 
`Use low GPU memory version of code`

**Comment by martel80** [comment]
I'm still experiencing the same issue. 

I do see Use low GPU memory version of code

I also tried with CPU and it also crashed.

**Comment by ZFTurbo** [comment]
> I downloaded the new version of Code.
> I'm still experiencing the same issue.
> I do see Use low GPU memory version of code
> I also tried with CPU and it also crashed.

1) Which GPU do you have?
2) Can you try with single ONNX option?

**Comment by martel80** [comment]
> > I downloaded the new version of Code.
> > I'm still experiencing the same issue.
> > I do see Use low GPU memory version of code
> > I also tried with CPU and it also crashed.
> 
>     1. Which GPU do you have?
> 
>     2. Can you try with single ONNX option?


WIN 10 22H2
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
16GB RAM

GPU: RTX 3060


I will try with ONNX now.

**Comment by ZFTurbo** [comment]
How much GPU memory?

**Comment by martel80** [comment]
> How much GPU memory?

12 GB GDDR6

I tried with Single ONNX and it also crashed.

**Comment by ZFTurbo** [comment]
Can you show me the log? Put in run.bat on the 2nd line: "cmd". It will keep console open after crash.

**Comment by martel80** [comment]
> Can you show me the log? Put in run.bat on the 2nd line: "cmd". It will keep console open after crash.


C:\MVSep-MDX23>"./Miniconda/python.exe" gui.py
GPU use: 0
Use low GPU memory version of code
Use device: cuda:0
Use single vocal ONNX
Go for: C:/MVSep-MDX23/01 - Sean Price, M-Phazes - Bag of Shit (feat. Loudmouf Choir)(Explicit).flac
Input audio: (2, 7537326) Sample rate: 44100
Model path: C:\MVSep-MDX23/models/Kim_Vocal_1.onnx
Device: cuda:0 Chunk size: 1000000
C:\MVSep-MDX23\inference.py:128: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  mix_waves = torch.tensor(mix_waves, dtype=torch.float32).to(device)
2023-05-15 14:21:22.0004569 [E:onnxruntime:, sequential_executor.cc:494 onnxruntime::ExecuteKernel] Non-zero status code returned while running FusedConv node. Name:'Conv_61' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 11796480

Traceback (most recent call last):
  File "C:\MVSep-MDX23\gui.py", line 36, in run
    predict_with_model(self.options)
  File "C:\MVSep-MDX23\inference.py", line 804, in predict_with_model
    result, sample_rates = model.separate_music_file(audio.T, sr, update_percent_func, i, len(options['input_audio']))
  File "C:\MVSep-MDX23\inference.py", line 587, in separate_music_file
    sources1 = demix_full(
  File "C:\MVSep-MDX23\inference.py", line 160, in demix_full
    sources = demix_base(mix_part, device, models, infer_session)
  File "C:\MVSep-MDX23\inference.py", line 133, in demix_base
    res = _ort.run(None, {'input': stft_res.cpu().numpy()})[0]
  File "C:\MVSep-MDX23\Miniconda\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedConv node. Name:'Conv_61' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 11796480

C:\MVSep-MDX23>cmd
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

C:\MVSep-MDX23>

**Comment by martel80** [comment]
And sorry for the song name, its just the first FLAC I found on my list haha :)

**Comment by martel80** [comment]
My apologies, apparently I only have 8 GB of DDR6 on my GPU.

I just checked in Task Manager and its written 8 GB. Not 12 GB.

Could it be the issue?

**Comment by lucellent** [comment]
> My apologies, apparently I only have 8 GB of DDR6 on my GPU.
> 
> I just checked in Task Manager and its written 8 GB. Not 12 GB.
> 
> Could it be the issue?
> 
> EDIT: I'm confused now, I have one window that says 8 GB and the other one says 14 GB.
> 
> ![image](https://user-images.githubusercontent.com/132940334/238438267-0e7adb9f-7b6e-40fa-aeb7-2e4f3c8b4345.png)
> 
> ![image](https://user-images.githubusercontent.com/132940334/238438368-ce534f27-6022-4bf3-a31d-6bd73b617820.png)

You have 6GB of VRAM. GPU 0 is your integrated GPU, inside of the CPU.

**Comment by ZFTurbo** [comment]
Actually you have only 6 GB. Yes, it can be an issue...

**Comment by ZFTurbo** [comment]
Can you check during run in task manager where the memory is allocated. intel or NVIDIA?

**Comment by martel80** [comment]
Well, there you go. We found out why everything crash. And I thought I had a decent laptop.

Its about to become a very expensive door holder, let me tell you that.

Back to UVR I guess. 

Sorry for the troubles, I genuinely didn't know I had a Computosaur

**Comment by martel80** [comment]
> 

![image](https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/assets/132940334/1e60ce4d-e01c-48bc-b0c1-295ae1519f60)

**Comment by lucellent** [comment]
Mine crashes after the following:

1. Click on start separation
2. Separation fails (already mentioned the issue)
3. Click Stop separation
4. Click start separation again
5. Crash

<img width="928" alt="Screenshot_37" src="https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/assets/38135928/f7b042d1-42f9-42bc-ac0e-6ded27b0fc7a">

**Comment by ZFTurbo** [comment]
> Mine crashes after the following:
> 
>     1. Click on start separation
> 
>     2. Separation fails (already mentioned the issue)
> 
>     3. Click Stop separation
> 
>     4. Click start separation again
> 

1. Don't use "Stop separation"
2. Why do you think separation fails? Can you wait 5-10 minutes? From log I can't see any fail.

**Comment by lucellent** [comment]
> > Mine crashes after the following:
> > ```
> > 1. Click on start separation
> > 
> > 2. Separation fails (already mentioned the issue)
> > 
> > 3. Click Stop separation
> > 
> > 4. Click start separation again
> > ```
> 
> 1. Don't use "Stop separation"
> 2. Why do you think separation fails? Can you wait 5-10 minutes? From log I can't see any fail.

It fails due to the same issue as others, displayed in the CMD, but I have 8GB of VRAM
I will try waiting this time but GPU usage goes down after a few seconds after the error message

**Comment by lucellent** [comment]
Could it have to do with the fact it converts files to 32bit?

**Comment by lucellent** [comment]
Ok, you're right. 
It actually processed successfully, with default chunk size (1,000,000) and NO single onnx

**Comment by martel80** [comment]
> Ok, you're right. It actually processed successfully, with default chunk size (1,000,000) and NO single onnx

How long did it take to complete the whole seperation?

**Comment by martel80** [comment]
> So now we know 8 GB is ok 6 GB is not ok. I think with single ONNX it probably should work at 6 GB too.

It doesnt. I tried and it failed. Thats the one I pasted up top when you asked.

**Comment by lucellent** [comment]
> > Ok, you're right. It actually processed successfully, with default chunk size (1,000,000) and NO single onnx
> 
> How long did it take to complete the whole seperation?

6-10 minutes

Now that I think about it it took the same time as with Demucs 4 ht model in UVR GUI, that's why

did you try lower chunk size?

**Comment by martel80** [comment]
> > > Ok, you're right. It actually processed successfully, with default chunk size (1,000,000) and NO single onnx
> > 
> > 
> > How long did it take to complete the whole seperation?
> 
> 6-10 minutes
> 
> Now that I think about it it took the same time as with Demucs 4 ht model in UVR GUI, that's why
> 
> did you try lower chunk size?

See, that's the part that really puzzle me as it took exactly 1 min 07 seconds to separate that same file with htdemucs_6s

It took exactly 4 min 19 sec to separate that same file with htdemucs_ft
![image](https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/assets/132940334/1c6cb722-569f-4451-89f9-4ff6390a5e9d)

Both on GPU Conversion

So how come it take longer on your side yet you are able to separate them and it take less time on my side ?

I dont understand the logic here.

**Comment by lucellent** [comment]
> 



> > > > Ok, you're right. It actually processed successfully, with default chunk size (1,000,000) and NO single onnx
> > > 
> > > 
> > > How long did it take to complete the whole seperation?
> > 
> > 
> > 6-10 minutes
> > Now that I think about it it took the same time as with Demucs 4 ht model in UVR GUI, that's why
> > did you try lower chunk size?
> 
> See, that's the part that really puzzle me as it took exactly 1 min 07 seconds to separate that same file with htdemucs_6s
> 
> It took exactly 4 min 19 sec to separate that same file with htdemucs_ft 
> 
> Both on GPU Conversion
> 
> So how come it take longer on your side yet you are able to separate them and it take less time on my side ?
> 
> I dont understand the logic here.

ZFTurbo's repo is more resource hungry, that's how I understand it

try with less chunks, someone else posted earlier here how to edit the file to use manual chunks

**Comment by ZFTurbo** [comment]
I use much larger overlap for all models. That's why they are slower.

**Comment by martel80** [comment]
All right. With a chunk size of 10000, I was able to complete the separation in exactly 10 minutes and 05 seconds.

I'm listening to the drum tracks on both and it seems like there's a lot more leak on the MVSEP compared to the htdemucs_ht.

You can listen to it for yourself here:

[https://1drv.ms/f/s!AtfvmPHCKb6a7QP-Jj1b7p_8xeWQ?e=6ikzqO](url)

Does chunk affect the quality of the separation? Or would it be ONNX ? There's a lot more bleeding in the MVSEP.

**Comment by lucellent** [comment]
Processing a second track after a successful first one results in the same issue as martel80
![image](https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model/assets/38135928/7119d423-9a91-4938-9636-87a1b1d3ea37)
