### ISSUE TITLE
How do I enable CPU over GPU?

### ISSUE THREAD

**Issue by ConsentKF** [ZFTurbo/MVSEP-MDX23-music-separation-model#18]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

I can't open the gui because the bat file does not find a GPU source (AMD), not sure how to enable CPU useage before the gui opens?

**Comment by ZFTurbo** [comment]
Can you post full error message? I'm interested in line numbers.

**Comment by Glammerocity** [comment]
Same issue for me.

C:\Users\Glammerocity\Desktop\MVSep>"./Miniconda/python.exe" gui.py
GPU use: 0
Version: 1.0.1
Traceback (most recent call last):
  File "C:\Users\Glammerocity\Desktop\MVSep\gui.py", line 411, in <module>
    create_dialog()
  File "C:\Users\Glammerocity\Desktop\MVSep\gui.py", line 319, in create_dialog
    t = torch.cuda.get_device_properties(0).total_memory / (1024 * 1024 * 1024)
  File "C:\Users\Glammerocity\Desktop\MVSep\Miniconda\lib\site-packages\torch\cuda\__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\Users\Glammerocity\Desktop\MVSep\Miniconda\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


I also got this warning. I'm useless enough not to know how to add directory to PATH:

  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'C:\Users\Glammerocity\Desktop\MVSep\Miniconda\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by kidgamer120** [comment]
Same again,

**Comment by ZFTurbo** [comment]
What is your GPU and what's the version of your driver?

**Comment by Glammerocity** [comment]
AMD Radeon Vega 8
Driver version 27.20.1028.1

**Comment by ZFTurbo** [comment]
You need NVIDIA GPU card to use CUDA. Otherwise you must run on CPU with --cpu key (it will be slow).

**Comment by Kenn-K** [comment]
where exactly do i enter the --cpu key? i've tried adding it to the end of the BAT, everything... it's still looking for NVIDIA
