### ISSUE TITLE
How to use this on linux?

### ISSUE THREAD

**Issue by sleeplessKomodo** [ZFTurbo/MVSEP-MDX23-music-separation-model#43]
This uses python, so it should be multi-platform, so I started up the web-ui thinking it would "just work" but I was clearly mistaken. I installed all the dependencies in a python virtual environment, so it theoretically should work. 

Is this at all useable on linux? I already use demucs, that uses the htdemucs model, and that works just fine on my machine.

**Comment by partofthething** [comment]
What errors did you get? I was able to fire up the GUI and web-ui on ubuntu 24.04 but am getting errors running inference related to unpickling the model.

```
Traceback (most recent call last):
  File "/home/nick/repos/MVSEP-MDX23-music-separation-model/inference.py", line 900, in <module>
    predict_with_model(options)
  File "/home/nick/repos/MVSEP-MDX23-music-separation-model/inference.py", line 838, in predict_with_model
    result, sample_rates = model.separate_music_file(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/repos/MVSEP-MDX23-music-separation-model/inference.py", line 579, in separate_music_file
    model_vocals = load_model(model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venvs/mvsep/lib/python3.12/site-packages/demucs/states.py", line 59, in load_model
    package = torch.load(path, 'cpu')
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/venvs/mvsep/lib/python3.12/site-packages/torch/serialization.py", line 1470, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL demucs.htdemucs.HTDemucs was not an allowed global by default. Please use `torch.serialization.add_safe_globals([HTDemucs])` or the `torch.serialization.safe_globals([HTDemucs])` context manager to allowlist this global if you trust this class/function
```

**Comment by ksherlock** [comment]
demucs hasn't been updated in a few years (and probably won't ever be given that the developer is no longer at facebook).  You need to use an older version of torch (< 3.6) or update that line to `package = torch.load(path, 'cpu', weights_only=False)`.
