### ISSUE TITLE
Model Crashes When Starting the Separation

### ISSUE THREAD

**Issue by ZeeroDevo** [ZFTurbo/MVSEP-MDX23-music-separation-model#9]
I use a Shadow Cloud PC that's an **_RTX A4500 20GB VRAM_** and I want to use this model to create my dataset for RVC but for unknown reasons **_it crashes when I start separation_**. It seems like #4 has the same situation too so I suspect it doesn't use my GPU but here are the error codes that displayed on CMD.

I also wanna ask how do we apply the arguments like --large_gpu?

CMD LOG:

`C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip>"./Miniconda/python.exe" gui.py
GPU use: 0
Use low GPU memory version of code
Use device: cuda:0
Go for: C:/Users/Shadow/Downloads/Music/Golden Hour - JVKE ｜ Song Cover by SuRge.wav
Input audio: (2, 9257472) Sample rate: 44100
Traceback (most recent call last):
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\gui.py", line 36, in run
    predict_with_model(self.options)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\inference.py", line 804, in predict_with_model
    result, sample_rates = model.separate_music_file(audio.T, sr, update_percent_func, i, len(options['input_audio']))
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\inference.py", line 554, in separate_music_file
    torch.hub.download_url_to_file(remote_url, model_folder + '04573f0d-f3cf25b2.th')
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Shadow\Downloads\MDX23\MVSep-MDX23.zip\Miniconda\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>`

**Comment by ZFTurbo** [comment]
The problem is actually not with model but with downloading Neural Net weights from internet.

**Comment by ZFTurbo** [comment]
May be this will help:
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
